# Stage 1: Build Angular app
FROM node:18-alpine AS build

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine

COPY --from=build /app/dist/searchengine/browser /usr/share/nginx/html

COPY src/main/frontend/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
