services:
  opensearch-node:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_SECURITY_ADMIN_PASSWORD=MyStrongPassword123!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data1:/usr/share/opensearch/data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: opensearch_dashboards
    ports:
      - "5601:5601"
    depends_on:
      - opensearch-node
    environment:
      - OPENSEARCH_HOSTS=https://opensearch-node:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=MyStrongPassword123!
      - OPENSEARCH_SSL_VERIFICATIONMODE=none

  postgres-db:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: searchdb
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: searchengine_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - opensearch-node
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/searchdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      OPENSEARCH_HOSTS: https://opensearch-node:9200
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: MyStrongPassword123!

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile-angular
    container_name: searchengine_angular
    ports:
      - "4200:80"
    depends_on:
      - web

  postman:
    build:
      context: .
      dockerfile: Dockerfile-postman-cli
    container_name: postman_cli
    depends_on:
      - web
    command: >
      sh -c "
        echo 'Waiting for backend...' &&
        until curl -s http://web:8080/search/test; do sleep 5; done &&
        postman collection run ./postman-tests/collection.json \
          --env-var baseUrl=http://web:8080 --verbose
      "

volumes:
  opensearch-data1:
  pg_data:
